### ISSUE TITLE
Custom Components are deprecated

### ISSUE THREAD

**Issue by askpatrickw** [nealcarney/ESPHome-MaxxFan-controller#11]
<img width="511" alt="Image" src="https://github.com/user-attachments/assets/681bfd88-4060-4367-9dcf-a579d67bd17c" />

https://esphome.io/guides/contributing#a-note-about-custom-components

It affects all the outputs.

```yaml
output:
    # Custom output for when power changed
    - platform: custom
      type: binary
      lambda: |-
          auto my_power_output = new PowerOutput();
          App.register_component(my_power_output);
          return {my_power_output};
      outputs:
          id: output_power
    # Custom output for when speed changed
    - platform: custom
      type: float
      lambda: |-
          auto my_speed_output = new SpeedOutput();
          App.register_component(my_speed_output);
          return {my_speed_output};
      outputs:
          id: output_speed
    # Custom output for when direction changed
    - platform: custom
      type: binary
      lambda: |-
          auto my_direction_output = new DirectionOutput();
          App.register_component(my_direction_output);
          return {my_direction_output};
      outputs:
          id: output_direction
    # Custom output for when cover changed
    - platform: custom
      type: binary
      lambda: |-
          auto my_cover_output = new CoverOutput();
          App.register_component(my_cover_output);
          return {my_cover_output};
      outputs:
          id: output_cover
```

I'll work out a plan ...
